### ISSUE TITLE
JSON decoding error in parsing flow and indicator ids

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/USEEIO_API#17]
testing a go build on localhost from the flowupdate branch with data from the USEEIOv2.0 model build with the [useeior/v2-alpha branch](https://github.com/USEPA/useeior/tree/v2-alpha), the test_indicators.py and test_flows.py are failing with a JSONDecodeError

```
INFO:root:check indicator 3 in model USEEIOv2.0

Error
Traceback (most recent call last):
  File "C:\Users\wesle\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\wesle\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 615, in run
    testMethod()
  File "C:\Users\wesle\USEEIO_API\python\tests\test_indicators.py", line 39, in test_get_indicator
    same = client.get_indicator(model_id, indicator['id'])
  File "C:\Users\wesle\USEEIO_API\python\useeioapi\client.py", line 36, in get_indicator
    return self.__get_json('/%s/indicators/%s' % (model_id, iid))
  File "C:\Users\wesle\USEEIO_API\python\useeioapi\client.py", line 75, in __get_json
    return r.json()
  File "C:\Users\wesle\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\wesle\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\wesle\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)
```

**Comment by msrocka** [comment]
I updated the indicator route so that it can handle the new indicator IDs (they contain spaces and slashes): https://github.com/USEPA/USEEIO_API/commit/c7cf05dc137184ba454b9b681ad9dde45ee8e7d3

This should fix the failing indicator test.

Regarding the failing test with the flows:  The format of the `flows.csv` file is different than what the API currently understands: https://github.com/USEPA/USEEIO_API/blob/master/go/useeioapi/flows.go#L46

It had `Category` and `SubCategory` before and now just `Context` (which is much better). So I would update the server for this, right? (we have the release tag, so updating it should be not a problem).

**Comment by WesIngwersen** [comment]
I realized I have already updated that one in the flow_update branch. I will make the pull request for you to review

**Comment by msrocka** [comment]
Seems to be all good now:

![image](https://user-images.githubusercontent.com/3520062/105703993-5e3a6c00-5f0e-11eb-9aa4-9f61d1e1f54d.png)
